import {
  Shirt,
  Smartphone,
  Plane,
  Utensils,
  Sparkles,
  Home,
  BookOpen,
  Heart,
  Package,
  Car,
  Baby,
  Gift,
  Film,
  Music,
  Gamepad2,
  Briefcase,
  Camera,
  Coffee,
  ShoppingCart,
  Star,
  Tag,
  Trash2,
  User,
  Wallet,
  Wifi,
  Zap,
  Headphones,
  Leaf,
  Moon,
  Sun,
  Globe,
  MapPin,
  //Truck,
  Book,
  Airplay,
  Anchor,
  BatteryCharging,
  Bell,
  BellOff,
  Bookmark,
  Calendar,
  CheckCircle,
  Clock,
  CreditCard,
  Database,
  Download,
  Eye,
  Filter,
  //Fire,
  Globe2,
  Hash,
  Image,
  Info,
  Key,
  Layers,
  Link,
  Loader,
  Lock,
  Mail,
  Map,
  Maximize,
  Minimize,
  Phone,
  PieChart,
  PlusCircle,
  Power,
  RefreshCcw,
  Repeat,
  Search,
  Server,
  Shield,
  ShoppingBag,
  Sliders,
  SmartphoneCharging,
  StarHalf,
  ToggleLeft,
  Trash,
  TrendingUp,
  Truck,
  Unlock,
  Upload,
  UserCheck,
  UserPlus,
  Video,
  Wine,
} from 'lucide-react';
import React from 'react';

// Central map of icon names to Lucide components
export const iconMap: { [key: string]: React.ElementType } = {
  shirt: Shirt,
  smartphone: Smartphone,
  plane: Plane,
  utensils: Utensils,
  sparkles: Sparkles,
  home: Home,
  'book-open': BookOpen,
  heart: Heart,
  car: Car,
  baby: Baby,
  gift: Gift,
  film: Film,
  music: Music,
  gamepad2: Gamepad2,
  briefcase: Briefcase,
    camera: Camera,
  coffee: Coffee,
  shopping_cart: ShoppingCart,
  star: Star,
  tag: Tag,
  trash2: Trash2,
  user: User,
  wallet: Wallet,
  wifi: Wifi,
  zap: Zap,
  headphones: Headphones,
  leaf: Leaf,
  moon: Moon,
  sun: Sun,
  globe: Globe,
  map_pin: MapPin,
  //truck: Truck,
  book: Book,
  airplay: Airplay,
  anchor: Anchor,
  battery_charging: BatteryCharging,
  bell: Bell,
  bell_off: BellOff,
  bookmark: Bookmark,
  calendar: Calendar,
  check_circle: CheckCircle,
  clock: Clock,
  credit_card: CreditCard,
  database: Database,
  download: Download,
  eye: Eye,
  filter: Filter,
  //fire: Fire,
  globe2: Globe2,
  hash: Hash,
  image: Image,
  info: Info,
  key: Key,
  layers: Layers,
  link: Link,
  loader: Loader,
  lock: Lock,
  mail: Mail,
  map: Map,
  maximize: Maximize,
  minimize: Minimize,
  phone: Phone,
  pie_chart: PieChart,
  plus_circle: PlusCircle,
  power: Power,
  refresh_ccw: RefreshCcw,
  repeat: Repeat,
  search: Search,
  server: Server,
  shield: Shield,
  shopping_bag: ShoppingBag,
  sliders: Sliders,
  smartphone_charging: SmartphoneCharging,
  star_half: StarHalf,
  toggle_left: ToggleLeft,
  trash: Trash,
  trending_up: TrendingUp,
  unlock: Unlock,
  upload: Upload,
  user_check: UserCheck,
  user_plus: UserPlus,
  video: Video,
  wine: Wine,
  package: Package, 
};

// Options for dropdowns in the admin panel
export const iconOptions = [
  { value: 'shirt', label: 'Fashion', icon: Shirt },
  { value: 'smartphone', label: 'Electronics', icon: Smartphone },
  { value: 'plane', label: 'Travel', icon: Plane },
  { value: 'utensils', label: 'Food', icon: Utensils },
  { value: 'sparkles', label: 'Beauty', icon: Sparkles },
  { value: 'home', label: 'Home', icon: Home },
  { value: 'book-open', label: 'Books', icon: BookOpen },
  { value: 'heart', label: 'Health', icon: Heart },
  { value: 'car', label: 'Automotive', icon: Car },
  { value: 'baby', label: 'Baby Products', icon: Baby },
  { value: 'gift', label: 'Gifts & Occasions', icon: Gift },
  { value: 'film', label: 'Entertainment', icon: Film },
  { value: 'music', label: 'Music', icon: Music },
  { value: 'gamepad2', label: 'Gaming', icon: Gamepad2 },
  { value: 'briefcase', label: 'Business & Office', icon: Briefcase },
  { value: 'package', label: 'General', icon: Package },
   { value: 'camera', label: 'Photography', icon: Camera },
  { value: 'coffee', label: 'Cafe & Drinks', icon: Coffee },
  { value: 'shopping_cart', label: 'Shopping', icon: ShoppingCart },
  { value: 'star', label: 'Favorites', icon: Star },
  { value: 'tag', label: 'Tags & Labels', icon: Tag },
  { value: 'trash2', label: 'Trash & Delete', icon: Trash2 },
  { value: 'user', label: 'User Profile', icon: User },
  { value: 'wallet', label: 'Finance & Wallet', icon: Wallet },
  { value: 'wifi', label: 'Connectivity', icon: Wifi },
  { value: 'zap', label: 'Energy & Power', icon: Zap },
  { value: 'headphones', label: 'Audio & Music', icon: Headphones },
  { value: 'leaf', label: 'Nature & Eco', icon: Leaf },
  { value: 'moon', label: 'Night Mode', icon: Moon },
  { value: 'sun', label: 'Day Mode', icon: Sun },
  { value: 'globe', label: 'Global & World', icon: Globe },
  { value: 'map_pin', label: 'Locations', icon: MapPin },
  //{ value: 'truck', label: 'Delivery & Transport', icon: Truck },
  { value: 'book', label: 'Reading & Education', icon: Book },
  { value: 'airplay', label: 'Streaming', icon: Airplay },
  { value: 'anchor', label: 'Stability & Anchor', icon: Anchor },
  { value: 'battery_charging', label: 'Battery & Power', icon: BatteryCharging },
  { value: 'bell', label: 'Notifications', icon: Bell },
  { value: 'bell_off', label: 'Mute Notifications', icon: BellOff },
  { value: 'bookmark', label: 'Bookmarks', icon: Bookmark },
  { value: 'calendar', label: 'Calendar & Events', icon: Calendar },
  { value: 'check_circle', label: 'Approval & Success', icon: CheckCircle },
  { value: 'clock', label: 'Time & Schedule', icon: Clock },
  { value: 'credit_card', label: 'Payments', icon: CreditCard },
  { value: 'database', label: 'Data & Storage', icon: Database },
  { value: 'download', label: 'Downloads', icon: Download },
  { value: 'eye', label: 'Visibility', icon: Eye },
  { value: 'filter', label: 'Filters', icon: Filter },
  //{ value: 'fire', label: 'Trending & Hot', icon: Fire },
  { value: 'globe2', label: 'Internet & Web', icon: Globe2 },
  { value: 'hash', label: 'Hashtag', icon: Hash },
  { value: 'image', label: 'Images & Photos', icon: Image },
  { value: 'info', label: 'Info & Help', icon: Info },
  { value: 'key', label: 'Security & Keys', icon: Key },
  { value: 'layers', label: 'Layers & Structure', icon: Layers },
  { value: 'link', label: 'Links & Connections', icon: Link },
  { value: 'loader', label: 'Loading & Progress', icon: Loader },
  { value: 'lock', label: 'Lock & Privacy', icon: Lock },
  { value: 'mail', label: 'Email & Messaging', icon: Mail },
  { value: 'map', label: 'Maps & Navigation', icon: Map },
  { value: 'maximize', label: 'Maximize', icon: Maximize },
  { value: 'minimize', label: 'Minimize', icon: Minimize },
  { value: 'phone', label: 'Phone & Calls', icon: Phone },
  { value: 'pie_chart', label: 'Statistics & Analytics', icon: PieChart },
  { value: 'plus_circle', label: 'Add & Create', icon: PlusCircle },
  { value: 'power', label: 'Power', icon: Power },
  { value: 'refresh_ccw', label: 'Refresh & Reload', icon: RefreshCcw },
  { value: 'repeat', label: 'Repeat & Loop', icon: Repeat },
  { value: 'search', label: 'Search', icon: Search },
  { value: 'server', label: 'Servers & Hosting', icon: Server },
  { value: 'shield', label: 'Security', icon: Shield },
  { value: 'shopping_bag', label: 'Shopping Bag', icon: ShoppingBag },
  { value: 'sliders', label: 'Settings & Controls', icon: Sliders },
  { value: 'smartphone_charging', label: 'Charging', icon: SmartphoneCharging },
  { value: 'star_half', label: 'Partial Favorites', icon: StarHalf },
  { value: 'toggle_left', label: 'Toggle Switch', icon: ToggleLeft },
  { value: 'trash', label: 'Trash & Delete', icon: Trash },
  { value: 'trending_up', label: 'Growth & Trends', icon: TrendingUp },
  { value: 'unlock', label: 'Unlock', icon: Unlock },
  { value: 'upload', label: 'Upload', icon: Upload },
  { value: 'user_check', label: 'User Verified', icon: UserCheck },
  { value: 'user_plus', label: 'Add User', icon: UserPlus },
  { value: 'video', label: 'Video & Media', icon: Video },
  { value: 'wine', label: 'Beverages', icon: Wine },
];
